name: UHCutils
version: 1.0
description: UHCutils Plugin
author: EXSolo
main: com.exsoloscript.uhcutils.UHCutils
database: false
commands:
  canjoin:
    usage: /canjoin
    description: Shows how many players can join
  whitelistall:
    usage: /whitelistall [clear]
    description: whitelists all players
  byebye:
    usage: /byebye <playerName>
    description: bans a player